# Generated by Django 5.0.2 on 2024-05-01 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('features_file', models.FilePathField()),
                ('target_smoother_file', models.FilePathField()),
                ('to_num_prep_file', models.FilePathField()),
                ('to_num_and_cat_prep_file', models.FilePathField()),
                ('predictor_file', models.FilePathField()),
                ('criterion', models.CharField(max_length=30)),
                ('target_n_days', models.IntegerField()),
                ('tickers_from_sector', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='published_utc',
            field=models.DateTimeField(),
        ),
        migrations.CreateModel(
            name='PortfolioComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(max_length=50)),
                ('part', models.FloatField()),
                ('creation_date', models.DateTimeField()),
                ('sector', models.CharField(max_length=50)),
                ('strategy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.strategy')),
            ],
        ),
    ]
